export const movies = [
  '127 Hours',
  '1917',
  '21 Jump Street',
  '22 Jump Street',
  '300',
  '42nd Street',
  'Air Force One',
  'Alien',
  'Aliens',
  'American Graffiti',
  'The American President',
  'American Sniper',
  'Analyze That',
  'Analyze This',
  'The Andromeda Strain',
  'Apollo 13',
  'Atomic Blonde',
  'Attack the Block',
  'Austin Powers in Goldmember',
  'Babe',
  'Baby Driver',
  'Back to the Future',
  'Back to the Future II',
  'Back to the Future III',
  'Bad Moms',
  'Barbie',
  'Barry Lyndon',
  'BASEketball',
  'Batman Begins',
  'Bells are Ringing',
  'Bend It Like Beckham',
  'Big',
  'Big Hero 6',
  'The Big Lebowski',
  'Big Trouble in Little China',
  'Birdman',
  'The Birds',
  'Birds Of Prey And The Fantabulous Emancipation Of One Harley Quinn',
  'The Black Hole',
  'Blade II',
  'Blade Runner 2049',
  'Blazing Saddles',
  'The Blind Side',
  'The Blues Brothers',
  'The Bodyguard',
  'Bohemian Rhapsody',
  'Boogie Nights',
  'Bottle Shock',
  'The Bourne Identity',
  'The Bourne Legacy',
  'The Bourne Supremacy',
  'The Bourne Ultimatum',
  'Brave',
  'Brazil',
  'The Breakfast Club',
  'The Bridge On the River Kwai',
  'Bubble Boy',
  'Butch Cassidy and the Sundance Kid',
  'Captain Phillips',
  'Cars 3',
  'Casino',
  'Changeling',
  'Chariots of Fire',
  'Children of Men',
  'Citizen Kane',
  'Cliffhanger',
  'Coco',
  'The Color Purple',
  'Conan the Barbarian',
  'Contact',
  'Contagion',
  'The Contender',
  'Crazy Rich Asians',
  'Crimson Tide',
  'The Dark Crystal',
  'The Dark Knight',
  'The Dark Tower',
  'Date Night',
  'Dave',
  'Dawn of The Planet of The Apes',
  'The Day of the Jackal',
  'Deadpool',
  'Deadpool 2',
  'The Devil Wears Prada',
  'Dial M for Murder',
  'Die Hard',
  'Die Hard 2',
  'Doctor Zhivago',
  'Dragonheart',
  'Dumb and Dumber',
  'Eddie the Eagle',
  'Elf',
  'Elvis',
  'Empire of the Sun',
  'Enter the Dragon',
  'The Equalizer 3',
  'Erin Brockovich',
  'Excalibur',
  'Fantastic Beasts and Where to Find Them',
  'The Fate Of The Furious',
  'The Favourite',
  'A Few Good Men',
  'Field of Dreams',
  'The Fifth Element',
  'Fight Club',
  'Finding Dory',
  'First Man',
  'Flash Gordon',
  'Fletch',
  'The French Connection',
  'Friday',
  'Friday Night Lights',
  'The Frighteners',
  'Game Night',
  'Ghostbusters',
  'Girls Trip',
  'Glory',
  'Gone Girl',
  'A Good Day to Die Hard',
  'The Good Dinosaur',
  'Goodfellas',
  'The Goonies',
  'Gravity',
  'The Greatest Showman',
  'The Green Mile',
  'Gremlins',
  'Groundhog Day',
  'Hairspray',
  'Hancock',
  'The Hangover',
  'Hanna',
  'Happy Feet',
  'Harriet',
  'Harry and the Hendersons',
  'Harry Potter and the Chamber of Secrets',
  'Harry Potter and the Goblet of Fire',
  'Harry Potter and the Half Blood Prince',
  'Harry Potter and the Order of the Phoenix',
  'Harry Potter and the Prisoner of Azkaban',
  'The Heat',
  'Hellboy',
  'Hidden Figures',
  'Hot Fuzz',
  'How to Train Your Dragon',
  'How to Train Your Dragon 2',
  'Hudson Hawk',
  'I Confess',
  'Ice Age',
  'Idiocracy',
  'Inception',
  'The Incredibles',
  'Incredibles 2',
  'Independence Day',
  'Indiana Jones and the Dial of Destiny',
  'Inside Out',
  'Insidious',
  'Invictus',
  'The Iron Giant',
  'Isle of Dogs',
  'IT',
  'IT Chapter Two',
  'Jason Bourne',
  'Jaws',
  'The Jerk',
  'Jerry Maguire',
  'The Jewel of the Nile',
  'Joe Versus The Volcano',
  'Jojo Rabbit',
  'The Judge',
  'Jumanji',
  'The Jungle Book',
  'Jupiter Ascending',
  'Jurassic Park',
  'Kiss Kiss Bang Bang',
  'Kubo and the Two Strings',
  'Kung Fu Panda',
  'Kung Fu Panda 3',
  'Labyrinth',
  'Lady In The Water',
  'Last Action Hero',
  'The Last Starfighter',
  'Legend',
  'The Lego Movie',
  'Life of Pi',
  'The Lion King',
  'Little Shop of Horrors',
  'Little Women',
  'Live Free or Die Hard',
  'Logan',
  'The Longest Day',
  'Looper',
  'The Lost Boys',
  'Love Actually',
  'Lucy',
  'Machete',
  'Magic Mike',
  'Maleficent',
  'The Martian',
  'The Marvels',
  'The Matrix',
  'The Matrix Reloaded',
  'The Matrix Revolutions',
  'Men In Black',
  'Miracle on 34th Street',
  'Miss Congeniality',
  'Moana',
  'Monsters University',
  'Moulin Rouge',
  'Mulan',
  'The Muppet Movie',
  'Murder by Death',
  'The Music Man',
  'My Cousin Vinny',
  'Noises Off',
  'North By Northwest',
  'Onward',
  'Oppenheimer',
  'The Outsiders',
  'Pacific Rim',
  'Paddington 2',
  'Parasite',
  'Pitch Perfect',
  'Poltergeist',
  'The Post',
  'Practical Magic',
  'Predator',
  'Predestination',
  'The Proposal',
  'Psycho',
  'Purple Rain',
  'Raising Arizona',
  'Ratatouille',
  'Ray',
  'Ready Player One',
  'Rebel Without a Cause',
  'Red Planet',
  'Red Sparrow',
  'The Revenant',
  'The Right Stuff',
  'Rise of the Planet of the Apes',
  'Risky Business',
  'A River Runs Through It',
  'The Rock',
  'Romancing the Stone',
  'Roxanne',
  'Run Lola Run',
  'Rush Hour',
  'Ruthless People',
  'Salt',
  'Say Anything',
  'Scent of a Woman',
  'The Secret Life of Pets',
  'The Secret Life of Walter Mitty',
  'The Secret of My Success',
  'Selena',
  'Serenity',
  'Seven Brides for Seven Brothers',
  'Shaun of the Dead',
  'The Shawshank Redemption',
  'The Shining',
  'Shrek',
  'Shrek 2',
  'Shrek Forever After',
  'Shrek the Third',
  'The Simpsons Movie',
  'Slumdog Millionaire',
  'Smokey and the Bandit',
  'Snatch',
  'Sneakers',
  'Snow White and The Seven Dwarfs',
  'So I Married an Axe Murderer',
  'The Social Network',
  'Song of the Sea',
  'The Sound of Music',
  'Soylent Green',
  'SPARTACUS',
  'Speed',
  'Spice World',
  'Spy Game',
  'A Star Is Born',
  'A Star Is Born',
  'Starship Troopers',
  'Strangers on a Train',
  'Stripes',
  'Stripes',
  'Superman Returns',
  'Suspicion',
  'Tangled',
  'Tenacious D in The Pick of Destiny',
  'Tenet',
  'They Live',
  'The Thing',
  'Thirteen Days',
  'Tomorrowland',
  'Tootsie',
  'Total Recall',
  'The Town',
  'Toy Story 2',
  'Toy Story 3',
  'Toy Story 4',
  'Trainwreck',
  'Tremors',
  'Tron',
  'True Lies',
  'Undercover Brother',
  'V for Vendetta',
  'Vacation',
  'Vegas Vacation',
  'Venom',
  'Vice',
  'Wall Street',
  'Walt Disney Animation Studios Short Films Collection',
  'Wanted',
  'War for the Planet of the Apes',
  'Weird Science',
  'The Witches of Eastwick',
  'The Wiz',
  'The Wolverine',
  'The Woman King',
  'Wonder Woman',
  'A Wrinkle in Time',
  'The Wrong Man',
  'X2',
  'Zootopia',
];
